import WalletProvider from "@/components/walletConnector/walletProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import { Web3Modal } from "@web3modal/react";
import { Black_Ops_One } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const black_ops_one = Black_Ops_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--black_ops_one",
});
const cls = (...classnames) => {
  return classnames.join(" ");
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cls(black_ops_one.variable)}>{children}</body>
    </html>
  );
}
